Update step06_deploy_maven.yml

diff --git a/.github/workflows/step06_deploy_maven.yml b/.github/workflows/step06_deploy_maven.yml
--- a/.github/workflows/step06_deploy_maven.yml
+++ b/.github/workflows/step06_deploy_maven.yml
@@ -66,20 +66,21 @@ jobs:
       - name: Transfer Artifact Jar via SCP
         run: |
           scp -i ~/private-key.pem app.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}
-
+          
       - name: Deploy and Start Application
         run: |
-          ssh -i ~/private-key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
-            sudo fuser -k 8080/tcp || true
-            nohup sudo java -jar /home/${{ secrets.REMOTE_USER }}/app.jar > /home/${{ secrets.REMOTE_USER }}/app.log 2>&1 &
-            sleep 30
-            if pgrep -f 'java -jar.*app.jar' > /dev/null
-            then
-              echo 'Application started successfully'
-              exit 0
-            else
-              echo 'Application failed to start'
-              cat /home/${{ secrets.REMOTE_USER }}/app.log
-              exit 1
-            fi
-          "
+         ssh -i ~/private-key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
+           sudo fuser -k 8080/tcp || true
+           cd /home/${{ secrets.REMOTE_USER }}
+           nohup sudo java -jar app.jar > app.log 2>&1 &
+           sleep 60
+           if pgrep -f 'java -jar.*app.jar' > /dev/null
+           then
+             echo 'Application started successfully'
+             exit 0
+           else
+             echo 'Application failed to start'
+             cat app.log
+             exit 1
+           fi
+           "
